#!/bin/bash
set -e
echo "Executing pip install..."
pip install requests
if command -v systemctl >/dev/null 2>&1; then
    systemctl daemon-reload
    systemctl enable example-deb.service
    systemctl start example-deb.service
fi
exit 0
